/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ArbitrumSvg {
    }
    interface ChainSelector {
        /**
          * Chain names to render
         */
        "chains": string;
    }
    interface EthereumSvg {
    }
    interface IconContainer {
        /**
          * The name of the icon to display
         */
        "icon": string;
        /**
          * size of the icon
         */
        "size": string;
    }
    interface PactsLink {
        /**
          * Size of the pacts font
         */
        "fontSize": string;
        /**
          * Size for the pacts icon
         */
        "iconSize": string;
    }
    interface PactsRow {
        /**
          * Size for the pacts icon
         */
        "iconSize": string;
        /**
          * Token name to display
         */
        "token": string;
    }
    interface PactsSvg {
    }
    interface UsdcSvg {
    }
    interface UsdtSvg {
    }
    interface WbtcSvg {
    }
}
declare global {
    interface HTMLArbitrumSvgElement extends Components.ArbitrumSvg, HTMLStencilElement {
    }
    var HTMLArbitrumSvgElement: {
        prototype: HTMLArbitrumSvgElement;
        new (): HTMLArbitrumSvgElement;
    };
    interface HTMLChainSelectorElement extends Components.ChainSelector, HTMLStencilElement {
    }
    var HTMLChainSelectorElement: {
        prototype: HTMLChainSelectorElement;
        new (): HTMLChainSelectorElement;
    };
    interface HTMLEthereumSvgElement extends Components.EthereumSvg, HTMLStencilElement {
    }
    var HTMLEthereumSvgElement: {
        prototype: HTMLEthereumSvgElement;
        new (): HTMLEthereumSvgElement;
    };
    interface HTMLIconContainerElement extends Components.IconContainer, HTMLStencilElement {
    }
    var HTMLIconContainerElement: {
        prototype: HTMLIconContainerElement;
        new (): HTMLIconContainerElement;
    };
    interface HTMLPactsLinkElement extends Components.PactsLink, HTMLStencilElement {
    }
    var HTMLPactsLinkElement: {
        prototype: HTMLPactsLinkElement;
        new (): HTMLPactsLinkElement;
    };
    interface HTMLPactsRowElement extends Components.PactsRow, HTMLStencilElement {
    }
    var HTMLPactsRowElement: {
        prototype: HTMLPactsRowElement;
        new (): HTMLPactsRowElement;
    };
    interface HTMLPactsSvgElement extends Components.PactsSvg, HTMLStencilElement {
    }
    var HTMLPactsSvgElement: {
        prototype: HTMLPactsSvgElement;
        new (): HTMLPactsSvgElement;
    };
    interface HTMLUsdcSvgElement extends Components.UsdcSvg, HTMLStencilElement {
    }
    var HTMLUsdcSvgElement: {
        prototype: HTMLUsdcSvgElement;
        new (): HTMLUsdcSvgElement;
    };
    interface HTMLUsdtSvgElement extends Components.UsdtSvg, HTMLStencilElement {
    }
    var HTMLUsdtSvgElement: {
        prototype: HTMLUsdtSvgElement;
        new (): HTMLUsdtSvgElement;
    };
    interface HTMLWbtcSvgElement extends Components.WbtcSvg, HTMLStencilElement {
    }
    var HTMLWbtcSvgElement: {
        prototype: HTMLWbtcSvgElement;
        new (): HTMLWbtcSvgElement;
    };
    interface HTMLElementTagNameMap {
        "arbitrum-svg": HTMLArbitrumSvgElement;
        "chain-selector": HTMLChainSelectorElement;
        "ethereum-svg": HTMLEthereumSvgElement;
        "icon-container": HTMLIconContainerElement;
        "pacts-link": HTMLPactsLinkElement;
        "pacts-row": HTMLPactsRowElement;
        "pacts-svg": HTMLPactsSvgElement;
        "usdc-svg": HTMLUsdcSvgElement;
        "usdt-svg": HTMLUsdtSvgElement;
        "wbtc-svg": HTMLWbtcSvgElement;
    }
}
declare namespace LocalJSX {
    interface ArbitrumSvg {
    }
    interface ChainSelector {
        /**
          * Chain names to render
         */
        "chains"?: string;
    }
    interface EthereumSvg {
    }
    interface IconContainer {
        /**
          * The name of the icon to display
         */
        "icon"?: string;
        /**
          * size of the icon
         */
        "size"?: string;
    }
    interface PactsLink {
        /**
          * Size of the pacts font
         */
        "fontSize"?: string;
        /**
          * Size for the pacts icon
         */
        "iconSize"?: string;
    }
    interface PactsRow {
        /**
          * Size for the pacts icon
         */
        "iconSize"?: string;
        /**
          * Token name to display
         */
        "token"?: string;
    }
    interface PactsSvg {
    }
    interface UsdcSvg {
    }
    interface UsdtSvg {
    }
    interface WbtcSvg {
    }
    interface IntrinsicElements {
        "arbitrum-svg": ArbitrumSvg;
        "chain-selector": ChainSelector;
        "ethereum-svg": EthereumSvg;
        "icon-container": IconContainer;
        "pacts-link": PactsLink;
        "pacts-row": PactsRow;
        "pacts-svg": PactsSvg;
        "usdc-svg": UsdcSvg;
        "usdt-svg": UsdtSvg;
        "wbtc-svg": WbtcSvg;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "arbitrum-svg": LocalJSX.ArbitrumSvg & JSXBase.HTMLAttributes<HTMLArbitrumSvgElement>;
            "chain-selector": LocalJSX.ChainSelector & JSXBase.HTMLAttributes<HTMLChainSelectorElement>;
            "ethereum-svg": LocalJSX.EthereumSvg & JSXBase.HTMLAttributes<HTMLEthereumSvgElement>;
            "icon-container": LocalJSX.IconContainer & JSXBase.HTMLAttributes<HTMLIconContainerElement>;
            "pacts-link": LocalJSX.PactsLink & JSXBase.HTMLAttributes<HTMLPactsLinkElement>;
            "pacts-row": LocalJSX.PactsRow & JSXBase.HTMLAttributes<HTMLPactsRowElement>;
            "pacts-svg": LocalJSX.PactsSvg & JSXBase.HTMLAttributes<HTMLPactsSvgElement>;
            "usdc-svg": LocalJSX.UsdcSvg & JSXBase.HTMLAttributes<HTMLUsdcSvgElement>;
            "usdt-svg": LocalJSX.UsdtSvg & JSXBase.HTMLAttributes<HTMLUsdtSvgElement>;
            "wbtc-svg": LocalJSX.WbtcSvg & JSXBase.HTMLAttributes<HTMLWbtcSvgElement>;
        }
    }
}
