name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: ConfigureGit
      run: |
        git config --global user.email "ci@pacts.tech"
        git config --global user.name "ci@$GITHUB_ACTOR"
    - name: CheckUser
      run: npm whoami
    - name: SetupNpmRc
      run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > .npmrc
    - name: Deps
      run: npm ci
    - name: Build
      run: npm run build-stencil
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm run release